#!bin/bash

#Author:Moses Karanja
#Date: september 25 2022

echo "We are now installing Sonarqube..."

echo "we are now updating yum.."
sudo yum update -yum
echo "we are now installing java.."
sudo yum install java-11-openjdk-devel -y
sudo yum install java-11-openjdk -y
echo "we are currently downloadind sonarqube.."
cd /opt
sudo yum install wget -y
sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.3.0.51899.zip
echo "installation in progress..."
sudo yum install unzip -y
sudo unzip /opt/sonarqube-9.3.0.51899.zip
sudo chown -R vagrant:vagrant /opt/sonarqube-9.3.0.51899
cd /opt/sonarqube-9.3.0.51899/bin/linux-x86-64
./sonar.sh start
echo "Sonarqube successfully installed"
